name: GPT Translate

on:
  issue_comment:
    types: [created]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read prompt from file
        id: prompt
        run: |
          prompt_value=$(cat .github/workflows/prompt.txt | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "prompt=$prompt_value" >> $GITHUB_OUTPUT
          
      - name: Debug - Print prompt and model
        run: |
          echo "=== Debug Information ==="
          echo "LLM_MODEL: ${{ secrets.LLM_MODEL }}"
          echo ""
          echo "=== Prompt Content ==="
          echo "${{ steps.prompt.outputs.prompt }}"
          echo "======================"

      - name: Run GPT Translate
        if: |
          contains(github.event.comment.body, '/gt')
        uses: 3ru/gpt-translate@v1.1.11
        with:
          apikey: ${{ secrets.API_KEY }}
          model: ${{ secrets.LLM_MODEL }}
          prompt: "${{ steps.prompt.outputs.prompt }}"
          basePath: ${{ secrets.BASE_URL }}
