name: GPT Translate by Input

on:
  workflow_dispatch:
    inputs:
      path:
        description: "The path to the directory containing the files to translate (e.g., docs/en/sql-reference/)"
        required: true
        default: "docs/en/sql-reference/"

permissions:
  id-token: write
  pull-requests: write
  checks: write
  statuses: write
  contents: write

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete all files in specified cn directory
        run: |
          TRANSLATION_DIR="${{ github.event.inputs.path }}"
          CN_DIR=$(echo $TRANSLATION_DIR | sed 's/en/cn/')
          echo "Deleting all files in $CN_DIR"
          rm -rf $CN_DIR
          echo "All files in $CN_DIR have been deleted."
          git add .

      - name: Get all files in specified directory
        id: check_missing
        run: |
          TRANSLATION_DIR="${{ github.event.inputs.path }}"
          echo "missing_md_files=$(find $TRANSLATION_DIR -type f \( -name '*.md' \) | sed -e 's/^/.\//' | tr '\n' ' ')" >> $GITHUB_OUTPUT
          echo "missing_json_files=$(find $TRANSLATION_DIR -type f \( -name '*.json' \) | sed -e 's/^/.\//' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Log Missing Files
        run: |
          echo "Markdown Files Missing: ${{ steps.check_missing.outputs.missing_md_files }}"
          echo "JSON Files Missing: ${{ steps.check_missing.outputs.missing_json_files }}"

      - name: Read prompt from file
        id: prompt
        run: |
          echo 'prompt<<EOF' >> $GITHUB_OUTPUT
          cat .github/workflows/prompt.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Debug - Save prompt to artifact
        run: |
          mkdir -p debug-output
          printf '%s' '${{ steps.prompt.outputs.prompt }}' > debug-output/prompt-variable.txt
          cp .github/workflows/prompt.txt debug-output/prompt-original.txt
          echo "LLM_MODEL: ${{ secrets.LLM_MODEL }}" > debug-output/debug-info.txt
          echo "BASE_URL: ${{ secrets.BASE_URL }}" >> debug-output/debug-info.txt
          echo "Input Path: ${{ github.event.inputs.path }}" >> debug-output/debug-info.txt
          echo "MD Files: ${{ steps.check_missing.outputs.missing_md_files }}" >> debug-output/debug-info.txt
          echo "JSON Files: ${{ steps.check_missing.outputs.missing_json_files }}" >> debug-output/debug-info.txt

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-prompt-${{ github.run_number }}
          path: debug-output/

      - name: Run GPT Translate
        uses: 3ru/gpt-translate@v1.1.11
        with:
          apikey: ${{ secrets.API_KEY }}
          model: ${{ secrets.LLM_MODEL }}
          inputFiles: "${{ steps.check_missing.outputs.missing_md_files }}${{ steps.check_missing.outputs.missing_json_files }}"
          outputFiles: "docs/cn/**/*.{md,json}"
          languages: "Simplified-Chinese"
          prompt: "${{ steps.prompt.outputs.prompt }}"
          basePath: ${{ secrets.BASE_URL }}
